version: '3.7'

services:
  mongo:
    image: mongo:6.0
    container_name: fastfood-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: fastfooddb
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: fastfood-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: fastfood-grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
volumes:
  mongo_data:

networks:
  monitoring:
